org: mollydeangelisjimenez
app: my-first-app

service: auth-servers

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  
functions:
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get
