const mockEvents = {
  city: {
    id: 11201,
    city: 'Brooklyn',
    lat: 40.7,
    lon: -73.99,
    state: 'NY',
    country: 'us',
    zip: '11201',
    member_count: 40247,
  },
  events: [
    {
      created: 1583720736000,
      duration: 10800000,
      id: 'cqrlqrybckblc',
      name: 'Williamsburg French',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1595975400000,
      local_date: '2020-07-28',
      local_time: '18:30',
      updated: 1583720736000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 14674432,
        name: 'SPRITZENHAUS 33',
        lat: 40.72313690185547,
        lon: -73.95297241210938,
        repinned: true,
        address_1: '33 Nassau Ave',
        city: 'Brooklyn',
        country: 'us',
        localized_country_name: 'USA',
        zip: '11222',
        state: 'NY',
      },
      is_online_event: false,
      group: {
        created: 1281014308000,
        name: 'Williamsburg French Language Group',
        id: 1686219,
        join_mode: 'open',
        lat: 40.709999084472656,
        lon: -73.94999694824219,
        urlname: 'Williamsburg-French-Language-Meetup-Group',
        who: 'Members',
        localized_location: 'Brooklyn, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern',
      },
      link: 'https://www.meetup.com/Williamsburg-French-Language-Meetup-Group/events/cqrlqrybckblc/',
      description: 'text inserted here',
      how_to_find_us: '**Ask the Bartenders**',
      visibility: 'public_limited',
      member_pay_fee: false,
    },
    {
      created: 1556548447000,
      duration: 7200000,
      id: 'mdzgxqybcjbkc',
      name: 'Proust Project: March - Gustave Flaubert\'s Madame Bovary; Optional Chateaubriand',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593284400000,
      local_date: '2020-06-27',
      local_time: '15:00',
      updated: 1556548447000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      is_online_event: false,
      group: {
        created: 1363023769000,
        name: 'Whisky + Books',
        id: 7567542,
        join_mode: 'open',
        lat: 40.720001220703125,
        lon: -73.9800033569336,
        urlname: 'Whisky-Books',
        who: 'Members',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern',
      },
      link: 'https://www.meetup.com/Whisky-Books/events/mdzgxqybcjbkc/',
      description: 'Text inserted again here',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1585515896000,
      duration: 7200000,
      id: '269734912',
      name: 'Anna Karenina by Leo Tolstoy',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593298800000,
      local_date: '2020-06-27',
      local_time: '19:00',
      updated: 1585515896000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 6,
      is_online_event: false,
      group: {
        created: 1363023769000,
        name: 'Whisky + Books',
        id: 7567542,
        join_mode: 'open',
        lat: 40.720001220703125,
        lon: -73.9800033569336,
        urlname: 'Whisky-Books',
        who: 'Members',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern',
      },
      link: 'https://www.meetup.com/Whisky-Books/events/269734912/',
      description: '<p>June is the month we traditionally do our really long book of the year. Now is the time to get cracking!</p> <p>The Book:</p> <p>The Whiskey(or vodka, maybe?) : TBD</p> <p>The Location: TBD. Just like our April meetup: If things have returned to normal and we can all go out again by June 27th (please please please!) I\'ll pick a place. Otherwise, we can all chat with Facebook messenger or have a video chat with Zoom, whichever one works for the most people. Comment below to let me know your preference.</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1591556305000,
      duration: 7200000,
      id: '271147631',
      name: 'All Levels French Conversation!',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1592672400000,
      local_date: '2020-06-20',
      local_time: '13:00',
      updated: 1591556958000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
        id: 26906060,
        name: 'Online event',
        repinned: false,
        country: '',
        localized_country_name: '',
      },
      is_online_event: true,
      group: {
        created: 1327003734000,
        name: 'Le French Club de Park Slope',
        id: 3133802,
        join_mode: 'open',
        lat: 40.66999816894531,
        lon: -73.98999786376953,
        urlname: 'LeFrenchClubdeParkSlope',
        who: 'Members',
        localized_location: 'Brooklyn, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern',
      },
      link: 'https://www.meetup.com/LeFrenchClubdeParkSlope/events/271147631/',
      description: '<p>If you would like to join this meetup on Zoom, please send me your email address in a private message on this site, so that I can send you the Zoom link and password. Thank you!</p> <p>Si vous aimeriez vous joindre au meetup sur Zoom, veuillez m\'envoyer un message privé sur ce site avec votre adresse e-mail, pour que je puisse vous envoyer le lien et le mot de passe pour Zoom. Merci !</p> ',
      visibility: 'public_limited',
      member_pay_fee: false,
    },
    {
      created: 1572624855000,
      duration: 7200000,
      id: 'zwctkrybcjbrb',
      name: 'French conversation intermediate (open to all levels)',
      rsvp_limit: 10,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1592056800000,
      local_date: '2020-06-13',
      local_time: '10:00',
      updated: 1572624855000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 7,
      venue: {
        id: 26711725,
        name: 'Yafa Cafe',
        lat: 40.649349212646484,
        lon: -74.00920104980469,
        repinned: false,
        address_1: '4415 4th Avenue ',
        city: 'Brooklyn',
        country: 'us',
        localized_country_name: 'USA',
        zip: '11220',
        state: 'NY',
      },
      is_online_event: false,
      group: {
        created: 1486993808000,
        name: 'Park Slope French Language Meetup',
        id: 22365228,
        join_mode: 'open',
        lat: 40.66999816894531,
        lon: -73.98999786376953,
        urlname: 'Park-Slope-French-Language-Meetup',
        who: 'Francophiles',
        localized_location: 'Brooklyn, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern',
      },
      link: 'https://www.meetup.com/Park-Slope-French-Language-Meetup/events/zwctkrybcjbrb/',
      description: '<p>Bonjour! We are a French conversation group. Perhaps you have studied French before and you want to brush up on your conversation skills? This may be the Meetup for you! While this Meetup is geared toward the intermediate level, we have a diverse community at all levels. You may consider yourself anywhere from a beginner* to an advanced level speaker. You may also consider yourself a fairly fluent speaker of French and would like to socialize with other Francophiles. We invite all levels to join us for a friendly two hours to discuss anything form daily life to current events, film, and Francophone culture and language. This is a social, no-pressure environment.</p> <p>*Beginners who attend may practice listening in somewhat of a mini language immersion and are also encouraged to ask questions. Our intermediate/advanced members are very friendly and happy to assist beginners when/if necessary.</p> <p>Each Meetup we learn something new-- from each other! Alors, rejoignez-nous pour une bonne discussion.</p> ',
      how_to_find_us: 'On the 45th street R train stop. Between 44th snd 45th street on 4th Avenue. ',
      visibility: 'public_limited',
      member_pay_fee: false,
    },
    {
      created: 1540448719000,
      duration: 7200000,
      id: 'qhnwkqybcjbvb',
      name: 'French conversation intermediate and advanced level',
      rsvp_limit: 6,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1592346600000,
      local_date: '2020-06-16',
      local_time: '18:30',
      rsvp_close_offset: 'PT2H30M',
      updated: 1540448719000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 25248371,
        name: 'Little Purity',
        lat: 40.66527557373047,
        lon: -73.98316955566406,
        repinned: true,
        address_1: '390 7th Ave',
        city: 'Brooklyn',
        country: 'us',
        localized_country_name: 'USA',
        zip: '',
        state: 'NY',
      },
      is_online_event: false,
      group: {
        created: 1486993808000,
        name: 'Park Slope French Language Meetup',
        id: 22365228,
        join_mode: 'open',
        lat: 40.66999816894531,
        lon: -73.98999786376953,
        urlname: 'Park-Slope-French-Language-Meetup',
        who: 'Francophiles',
        localized_location: 'Brooklyn, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern',
      },
      link: 'https://www.meetup.com/Park-Slope-French-Language-Meetup/events/qhnwkqybcjbvb/',
      description: 'text inserted a third time',
      visibility: 'public_limited',
      member_pay_fee: false,
    },
    {
      created: 1588998349000,
      duration: 1800000,
      id: 'nwcdsrybcjbnb',
      name: 'CANCELLED UNTIL FURTHER NOTICE: Free French Conversation WORKSHOP with Ruth',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1591812000000,
      local_date: '2020-06-10',
      local_time: '14:00',
      updated: 1588998349000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 26138718,
        name: 'New York Public Library',
        lat: 40.76079177856445,
        lon: -73.97736358642578,
        repinned: true,
        address_1: '18 W 53rd St',
        city: 'New York',
        country: 'us',
        localized_country_name: 'USA',
        zip: '10019',
        state: 'ny',
      },
      is_online_event: false,
      group: {
        created: 1318454724000,
        name: '! French New York City !',
        id: 2638322,
        join_mode: 'open',
        lat: 40.720001220703125,
        lon: -74,
        urlname: 'frenchies',
        who: 'frenchies',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern',
      },
      link: 'https://www.meetup.com/frenchies/events/nwcdsrybcjbnb/',
      description: '<p>THIS MEETUP HAS BEEN CANCELLED UNTIL FURTHER NOTICE.</p> ',
      how_to_find_us: 'The front desk staff will tell you to go downstairs and down the hall to Community Room-B. Ruth will display two small French flags on the table.',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1574466491000,
      duration: 7200000,
      id: 'fngllrybcjbbc',
      name: 'French conversation beginner Level',
      rsvp_limit: 10,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1592661600000,
      local_date: '2020-06-20',
      local_time: '10:00',
      rsvp_close_offset: 'PT11H15M',
      updated: 1574466491000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
        id: 26723463,
        name: 'Yafa Cafe',
        lat: 40.64875793457031,
        lon: -74.00980377197266,
        repinned: false,
        address_1: '4515 4th Avenue',
        city: 'Brooklyn',
        country: 'us',
        localized_country_name: 'USA',
        zip: '11220',
        state: 'NY',
      },
      is_online_event: false,
      group: {
        created: 1486993808000,
        name: 'Park Slope French Language Meetup',
        id: 22365228,
        join_mode: 'open',
        lat: 40.66999816894531,
        lon: -73.98999786376953,
        urlname: 'Park-Slope-French-Language-Meetup',
        who: 'Francophiles',
        localized_location: 'Brooklyn, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern',
      },
      link: 'https://www.meetup.com/Park-Slope-French-Language-Meetup/events/fngllrybcjbbc/',
      description: '<p>Are you a complete beginner in French? Or maybe, you\'ve studied French a very long time ago and you\'ve forgotten almost everything? Let\'s meet up to have discussions in basic French!</p> <p>Discussions will revolve mostly around daily life and will give you a chance to engage with others in a friendly, social setting while building your confidence in speaking French.</p> <p>Since Rachel has recently taken a new position in a French language school in White Plains, she will not be able to host all of the Meetups. However, she may return from time to time and will be present for our special events. In the meantime, to facilitate your learning and conversation practice, she will check-in on the site periodically and provide links to formal instruction. Rachel and I will also provide tips to study on your own if don\'t know where to start. : )</p> <p>This Meetup event is free of charge, however as we are meeting in a cafe and using their space, you should expect to purchase food and/or beverage as a typical customer.</p> ',
      visibility: 'public_limited',
      member_pay_fee: false,
    },
    {
      created: 1556548447000,
      duration: 7200000,
      id: 'mdzgxqybckbhc',
      name: 'Proust Project: March - Gustave Flaubert\'s Madame Bovary; Optional Chateaubriand',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1595703600000,
      local_date: '2020-07-25',
      local_time: '15:00',
      updated: 1556548447000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      is_online_event: false,
      group: {
        created: 1363023769000,
        name: 'Whisky + Books',
        id: 7567542,
        join_mode: 'open',
        lat: 40.720001220703125,
        lon: -73.9800033569336,
        urlname: 'Whisky-Books',
        who: 'Members',
        localized_location: 'New York, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern',
      },
      link: 'https://www.meetup.com/Whisky-Books/events/mdzgxqybckbhc/',
      description: '<p>Inspired by yesterday\'s meet-up discussion, a few of us are embarking on a Proust Project. The plan is to read a few books that influenced Proust before diving into his work. Please comment on selected books before we schedule them. Also toying with the idea of making this virtual - we talk about it online. Pre-Proust Schedule Year 1</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1554326642000,
      duration: 7200000,
      id: 'knzqvqybcjbmb',
      name: 'Writing Under the Influence',
      rsvp_limit: 30,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1591745400000,
      local_date: '2020-06-09',
      local_time: '19:30',
      updated: 1589916337000,
      utc_offset: -14400000,
      waitlist_count: 0,
      yes_rsvp_count: 12,
      venue: {
        id: 26906060,
        name: 'Online event',
        repinned: true,
        country: '',
        localized_country_name: '',
      },
      is_online_event: true,
      group: {
        created: 1496954556000,
        name: 'Writing Under the Influence',
        id: 24358872,
        join_mode: 'open',
        lat: 40.70000076293945,
        lon: -73.91999816894531,
        urlname: 'Writing-Under-Influence',
        who: 'Members',
        localized_location: 'Brooklyn, NY',
        state: 'NY',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Eastern',
      },
      link: 'https://www.meetup.com/Writing-Under-Influence/events/knzqvqybcjbmb/',
      description: '<p>Drunk driving is not cool, but drunk writing is! This is a community event for writers, with drinks! Work on your own stuff or use the creative writing prompts provided. We will have focused 20 minute writing sprints, with breaks in between, all in a video chat. (Until we return one day to our beloved Keep...)</p> <p>Link: ',
      how_to_find_us: 'https://us04web.zoom.us/j/463908305?pwd=L2FlOVBLVHc4TFJnd3ZmRzNSdCtjdz09',
      visibility: 'public',
      member_pay_fee: false,
    },
  ],
};

export { mockEvents };


